// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.603000,HLS_SYN_LAT=27,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3161,HLS_SYN_LUT=2097,HLS_VERSION=2023_2}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y,
        y_ap_vld,
        x
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_state7 = 28'd64;
parameter    ap_ST_fsm_state8 = 28'd128;
parameter    ap_ST_fsm_state9 = 28'd256;
parameter    ap_ST_fsm_state10 = 28'd512;
parameter    ap_ST_fsm_state11 = 28'd1024;
parameter    ap_ST_fsm_state12 = 28'd2048;
parameter    ap_ST_fsm_state13 = 28'd4096;
parameter    ap_ST_fsm_state14 = 28'd8192;
parameter    ap_ST_fsm_state15 = 28'd16384;
parameter    ap_ST_fsm_state16 = 28'd32768;
parameter    ap_ST_fsm_state17 = 28'd65536;
parameter    ap_ST_fsm_state18 = 28'd131072;
parameter    ap_ST_fsm_state19 = 28'd262144;
parameter    ap_ST_fsm_state20 = 28'd524288;
parameter    ap_ST_fsm_state21 = 28'd1048576;
parameter    ap_ST_fsm_state22 = 28'd2097152;
parameter    ap_ST_fsm_state23 = 28'd4194304;
parameter    ap_ST_fsm_state24 = 28'd8388608;
parameter    ap_ST_fsm_state25 = 28'd16777216;
parameter    ap_ST_fsm_state26 = 28'd33554432;
parameter    ap_ST_fsm_state27 = 28'd67108864;
parameter    ap_ST_fsm_state28 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [16:0] y;
output   y_ap_vld;
input  [16:0] x;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_126;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_124;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_123;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_122;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_121;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_120;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_118;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_117;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_116;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_115;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_114;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_113;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_112;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_111;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_110;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_109;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_108;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_106;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_105;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_104;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_103;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_102;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_101;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_100;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_99;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_98;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_95;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_94;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_93;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_92;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_91;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_90;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_89;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_88;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_87;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_86;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_85;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_84;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_83;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_82;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_81;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_79;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_78;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_77;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_76;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_75;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_74;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_73;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_72;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_71;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_70;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_69;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_68;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_67;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_66;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_65;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_64;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_63;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_62;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_61;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_60;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_59;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_58;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_57;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_56;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_55;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_54;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_53;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_52;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_51;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_50;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_48;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_47;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_46;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_45;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_44;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_43;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_42;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_41;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_40;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_39;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_38;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_37;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_36;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_35;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_34;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_33;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_32;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_31;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_30;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_29;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_28;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_27;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_26;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_25;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_24;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_23;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_22;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_21;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_20;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_19;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_18;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_17;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_16;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_15;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_14;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_13;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_12;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_11;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_10;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_9;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_8;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_7;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_6;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_5;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_4;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_3;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_2;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_1;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107_load_reg_2585;
wire   [14:0] tmp21_fu_343_p2;
reg   [14:0] tmp21_reg_2591;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125_load_reg_2596;
wire    ap_CS_fsm_state2;
reg   [14:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119_load_reg_2602;
wire   [14:0] tmp5_fu_508_p2;
reg   [14:0] tmp5_reg_2608;
wire   [14:0] tmp10_fu_520_p2;
reg   [14:0] tmp10_reg_2613;
wire   [14:0] tmp14_fu_532_p2;
reg   [14:0] tmp14_reg_2618;
wire   [14:0] tmp16_fu_544_p2;
reg   [14:0] tmp16_reg_2623;
wire   [14:0] tmp18_fu_561_p2;
reg   [14:0] tmp18_reg_2628;
wire   [15:0] trunc_ln15_fu_566_p1;
reg   [15:0] trunc_ln15_reg_2633;
wire    ap_CS_fsm_state3;
wire   [14:0] tmp2_fu_619_p2;
reg   [14:0] tmp2_reg_2638;
wire   [14:0] tmp7_fu_635_p2;
reg   [14:0] tmp7_reg_2643;
wire   [14:0] tmp12_fu_644_p2;
reg   [14:0] tmp12_reg_2648;
wire   [14:0] tmp61_fu_653_p2;
reg   [14:0] tmp61_reg_2653;
wire    ap_CS_fsm_state4;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96_load_reg_2658;
wire    ap_CS_fsm_state5;
wire   [14:0] tmp63_fu_695_p2;
reg   [14:0] tmp63_reg_2664;
wire   [14:0] tmp65_fu_734_p2;
reg   [14:0] tmp65_reg_2669;
wire    ap_CS_fsm_state6;
wire   [14:0] tmp67_fu_773_p2;
reg   [14:0] tmp67_reg_2674;
wire    ap_CS_fsm_state7;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_14_reg_2679;
wire    ap_CS_fsm_state8;
wire   [14:0] tmp69_fu_848_p2;
reg   [14:0] tmp69_reg_2684;
wire   [14:0] tmp28_fu_860_p2;
reg   [14:0] tmp28_reg_2689;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97_load_reg_2694;
wire    ap_CS_fsm_state9;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80_load_reg_2699;
wire   [14:0] tmp23_fu_989_p2;
reg   [14:0] tmp23_reg_2705;
wire   [14:0] tmp26_fu_1001_p2;
reg   [14:0] tmp26_reg_2710;
wire   [15:0] tmp133_fu_1018_p2;
reg   [15:0] tmp133_reg_2715;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_12_reg_2720;
wire    ap_CS_fsm_state10;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_19_reg_2726;
wire   [14:0] tmp78_fu_1171_p2;
reg   [14:0] tmp78_reg_2732;
wire   [15:0] tmp135_fu_1182_p2;
reg   [15:0] tmp135_reg_2737;
wire   [15:0] tmp38_fu_1194_p2;
reg   [15:0] tmp38_reg_2742;
wire   [15:0] tmp162_fu_1205_p2;
reg   [15:0] tmp162_reg_2747;
wire   [12:0] tmp180_fu_1217_p2;
reg   [12:0] tmp180_reg_2752;
wire   [14:0] tmp80_fu_1309_p2;
reg   [14:0] tmp80_reg_2757;
wire    ap_CS_fsm_state11;
wire   [15:0] tmp139_fu_1319_p2;
reg   [15:0] tmp139_reg_2762;
wire   [15:0] tmp164_fu_1330_p2;
reg   [15:0] tmp164_reg_2767;
wire   [12:0] tmp182_fu_1341_p2;
reg   [12:0] tmp182_reg_2772;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_18_reg_2777;
wire    ap_CS_fsm_state12;
wire   [14:0] tmp82_fu_1388_p2;
reg   [14:0] tmp82_reg_2782;
wire   [15:0] tmp141_fu_1399_p2;
reg   [15:0] tmp141_reg_2787;
reg   [15:0] p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49_load_reg_2792;
wire    ap_CS_fsm_state13;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_31_reg_2798;
wire   [14:0] trunc_ln39_33_fu_1573_p1;
reg   [14:0] trunc_ln39_33_reg_2803;
wire   [14:0] tmp84_fu_1594_p2;
reg   [14:0] tmp84_reg_2808;
wire   [14:0] tmp35_fu_1606_p2;
reg   [14:0] tmp35_reg_2813;
wire   [15:0] tmp143_fu_1617_p2;
reg   [15:0] tmp143_reg_2818;
wire   [15:0] tmp120_fu_1629_p2;
reg   [15:0] tmp120_reg_2823;
wire   [15:0] tmp166_fu_1640_p2;
reg   [15:0] tmp166_reg_2828;
wire   [12:0] tmp184_fu_1651_p2;
reg   [12:0] tmp184_reg_2833;
wire   [14:0] tmp31_fu_1813_p2;
reg   [14:0] tmp31_reg_2838;
wire    ap_CS_fsm_state14;
wire   [14:0] tmp32_fu_1819_p2;
reg   [14:0] tmp32_reg_2843;
wire   [14:0] tmp33_fu_1831_p2;
reg   [14:0] tmp33_reg_2848;
wire   [15:0] tmp147_fu_1840_p2;
reg   [15:0] tmp147_reg_2853;
wire   [15:0] tmp169_fu_1856_p2;
reg   [15:0] tmp169_reg_2858;
wire   [12:0] tmp187_fu_1873_p2;
reg   [12:0] tmp187_reg_2863;
wire   [14:0] tmp93_fu_1903_p2;
reg   [14:0] tmp93_reg_2868;
wire    ap_CS_fsm_state15;
wire   [15:0] tmp149_fu_1913_p2;
reg   [15:0] tmp149_reg_2873;
reg   [15:0] fir_ap_int_17_ap_int_17_shift_reg_7_load_reg_2878;
wire    ap_CS_fsm_state16;
wire   [14:0] tmp95_fu_2035_p2;
reg   [14:0] tmp95_reg_2883;
wire   [15:0] tmp171_fu_2063_p2;
reg   [15:0] tmp171_reg_2888;
wire   [12:0] tmp1891_fu_2078_p2;
reg   [12:0] tmp1891_reg_2894;
wire   [14:0] tmp97_fu_2117_p2;
reg   [14:0] tmp97_reg_2899;
wire    ap_CS_fsm_state17;
wire   [14:0] tmp99_fu_2156_p2;
reg   [14:0] tmp99_reg_2904;
wire    ap_CS_fsm_state18;
wire   [14:0] tmp101_fu_2202_p2;
reg   [14:0] tmp101_reg_2914;
wire    ap_CS_fsm_state19;
(* use_dsp48 = "no" *) wire   [15:0] add_ln39_2_fu_2218_p2;
reg   [15:0] add_ln39_2_reg_2919;
wire   [14:0] tmp103_fu_2256_p2;
reg   [14:0] tmp103_reg_2924;
wire    ap_CS_fsm_state20;
wire   [14:0] tmp105_fu_2295_p2;
reg   [14:0] tmp105_reg_2929;
wire    ap_CS_fsm_state21;
wire   [14:0] tmp107_fu_2334_p2;
reg   [14:0] tmp107_reg_2934;
wire    ap_CS_fsm_state22;
wire   [14:0] tmp109_fu_2373_p2;
reg   [14:0] tmp109_reg_2939;
wire    ap_CS_fsm_state23;
wire   [14:0] tmp111_fu_2412_p2;
reg   [14:0] tmp111_reg_2944;
wire    ap_CS_fsm_state24;
wire   [14:0] tmp113_fu_2451_p2;
reg   [14:0] tmp113_reg_2949;
wire    ap_CS_fsm_state25;
wire   [14:0] tmp115_fu_2490_p2;
reg   [14:0] tmp115_reg_2954;
wire    ap_CS_fsm_state26;
wire   [14:0] tmp117_fu_2534_p2;
reg   [14:0] tmp117_reg_2959;
wire    ap_CS_fsm_state27;
wire   [12:0] empty_58_fu_2540_p1;
reg   [12:0] empty_58_reg_2964;
wire   [14:0] trunc_ln33_fu_870_p1;
wire    ap_CS_fsm_state28;
wire   [14:0] tmp22_fu_337_p2;
wire   [14:0] tmp6_fu_502_p2;
wire   [14:0] tmp11_fu_514_p2;
wire   [14:0] tmp15_fu_526_p2;
wire   [14:0] tmp17_fu_538_p2;
wire   [14:0] tmp20_fu_550_p2;
wire   [14:0] tmp19_fu_555_p2;
wire   [14:0] trunc_ln39_fu_604_p1;
wire   [14:0] tmp4_fu_608_p2;
wire   [14:0] tmp3_fu_613_p2;
wire   [14:0] tmp9_fu_624_p2;
wire   [14:0] tmp8_fu_629_p2;
wire   [14:0] tmp13_fu_640_p2;
wire   [14:0] tmp1_fu_649_p2;
wire   [14:0] trunc_ln39_56_fu_686_p1;
wire   [14:0] tmp62_fu_690_p2;
wire   [14:0] trunc_ln39_55_fu_682_p1;
wire   [14:0] trunc_ln39_54_fu_725_p1;
wire   [14:0] tmp64_fu_729_p2;
wire   [14:0] trunc_ln39_53_fu_721_p1;
wire   [14:0] trunc_ln39_52_fu_764_p1;
wire   [14:0] tmp66_fu_768_p2;
wire   [14:0] trunc_ln39_51_fu_760_p1;
wire   [14:0] trunc_ln39_50_fu_839_p1;
wire   [14:0] tmp68_fu_843_p2;
wire   [14:0] trunc_ln39_49_fu_835_p1;
wire   [14:0] trunc_ln39_42_fu_827_p1;
wire   [14:0] trunc_ln39_41_fu_823_p1;
wire   [14:0] tmp29_fu_854_p2;
wire   [14:0] trunc_ln39_43_fu_831_p1;
wire   [14:0] trunc_ln39_48_fu_974_p1;
wire   [14:0] trunc_ln39_47_fu_970_p1;
wire   [14:0] trunc_ln39_46_fu_966_p1;
wire   [14:0] tmp25_fu_983_p2;
wire   [14:0] tmp24_fu_978_p2;
wire   [14:0] trunc_ln39_45_fu_962_p1;
wire   [14:0] trunc_ln39_44_fu_958_p1;
wire   [14:0] tmp27_fu_995_p2;
wire   [15:0] tmp131_fu_1006_p2;
wire   [15:0] tmp132_fu_1012_p2;
wire   [14:0] tmp77_fu_1167_p2;
wire   [14:0] trunc_ln39_40_fu_1151_p1;
wire   [15:0] tmp134_fu_1177_p2;
wire   [15:0] tmp39_fu_1188_p2;
wire   [15:0] tmp161_fu_1199_p2;
wire   [12:0] empty_57_fu_1163_p1;
wire   [12:0] empty_56_fu_1159_p1;
wire   [12:0] tmp179_fu_1211_p2;
wire   [12:0] empty_55_fu_1155_p1;
wire   [14:0] trunc_ln39_39_fu_1292_p1;
wire   [14:0] tmp79_fu_1304_p2;
wire   [14:0] trunc_ln39_38_fu_1288_p1;
wire   [15:0] tmp37_fu_1315_p2;
wire   [15:0] tmp123_fu_1324_p2;
wire   [12:0] empty_54_fu_1300_p1;
wire   [12:0] empty_53_fu_1296_p1;
wire   [12:0] tmp125_fu_1335_p2;
wire   [14:0] trunc_ln39_37_fu_1379_p1;
wire   [14:0] tmp81_fu_1383_p2;
wire   [14:0] trunc_ln39_36_fu_1375_p1;
wire   [15:0] tmp140_fu_1394_p2;
wire   [14:0] trunc_ln39_35_fu_1581_p1;
wire   [14:0] tmp83_fu_1589_p2;
wire   [14:0] trunc_ln39_34_fu_1577_p1;
wire   [14:0] trunc_ln39_26_fu_1561_p1;
wire   [14:0] trunc_ln39_25_fu_1557_p1;
wire   [14:0] tmp36_fu_1600_p2;
wire   [14:0] trunc_ln39_27_fu_1565_p1;
wire   [15:0] tmp142_fu_1612_p2;
wire   [15:0] tmp121_fu_1623_p2;
wire   [15:0] tmp165_fu_1635_p2;
wire   [12:0] empty_52_fu_1585_p1;
wire   [12:0] tmp183_fu_1646_p2;
wire   [12:0] empty_51_fu_1569_p1;
wire   [14:0] tmp85_fu_1809_p2;
wire   [14:0] trunc_ln39_32_fu_1801_p1;
wire   [14:0] trunc_ln39_31_fu_1797_p1;
wire   [14:0] trunc_ln39_30_fu_1793_p1;
wire   [14:0] trunc_ln39_29_fu_1789_p1;
wire   [14:0] trunc_ln39_28_fu_1785_p1;
wire   [14:0] tmp34_fu_1825_p2;
wire   [15:0] tmp119_fu_1836_p2;
wire   [15:0] tmp124_fu_1845_p2;
wire   [15:0] tmp168_fu_1851_p2;
wire   [12:0] empty_50_fu_1805_p1;
wire   [12:0] empty_49_fu_1781_p1;
wire   [12:0] tmp126_fu_1862_p2;
wire   [12:0] tmp186_fu_1868_p2;
wire   [12:0] empty_48_fu_1777_p1;
wire   [14:0] tmp30_fu_1899_p2;
wire   [15:0] tmp148_fu_1908_p2;
wire   [14:0] trunc_ln39_24_fu_2026_p1;
wire   [14:0] tmp94_fu_2030_p2;
wire   [14:0] trunc_ln39_23_fu_2022_p1;
wire   [15:0] tmp150_fu_2041_p2;
wire   [15:0] tmp170_fu_2058_p2;
wire   [12:0] empty_fu_2018_p1;
wire   [12:0] tmp188_fu_2069_p2;
wire   [12:0] empty_60_fu_2074_p1;
wire   [14:0] trunc_ln39_22_fu_2108_p1;
wire   [14:0] tmp96_fu_2112_p2;
wire   [14:0] trunc_ln39_21_fu_2104_p1;
wire   [14:0] trunc_ln39_20_fu_2147_p1;
wire   [14:0] tmp98_fu_2151_p2;
wire   [14:0] trunc_ln39_19_fu_2143_p1;
wire   [14:0] trunc_ln39_18_fu_2193_p1;
wire   [14:0] tmp100_fu_2197_p2;
wire   [14:0] trunc_ln39_17_fu_2189_p1;
wire   [15:0] empty_59_fu_2208_p2;
wire  signed [15:0] add_ln39_2_fu_2218_p0;
wire   [15:0] grp_fu_2574_p4;
wire   [15:0] tmp172_fu_2213_p2;
wire   [14:0] trunc_ln39_16_fu_2247_p1;
wire   [14:0] tmp102_fu_2251_p2;
wire   [14:0] trunc_ln39_15_fu_2243_p1;
wire   [14:0] trunc_ln39_14_fu_2286_p1;
wire   [14:0] tmp104_fu_2290_p2;
wire   [14:0] trunc_ln39_13_fu_2282_p1;
wire   [14:0] trunc_ln39_12_fu_2325_p1;
wire   [14:0] tmp106_fu_2329_p2;
wire   [14:0] trunc_ln39_11_fu_2321_p1;
wire   [14:0] trunc_ln39_10_fu_2364_p1;
wire   [14:0] tmp108_fu_2368_p2;
wire   [14:0] trunc_ln39_9_fu_2360_p1;
wire   [14:0] trunc_ln39_8_fu_2403_p1;
wire   [14:0] tmp110_fu_2407_p2;
wire   [14:0] trunc_ln39_7_fu_2399_p1;
wire   [14:0] trunc_ln39_6_fu_2442_p1;
wire   [14:0] tmp112_fu_2446_p2;
wire   [14:0] trunc_ln39_5_fu_2438_p1;
wire   [14:0] trunc_ln39_4_fu_2481_p1;
wire   [14:0] tmp114_fu_2485_p2;
wire   [14:0] trunc_ln39_3_fu_2477_p1;
wire   [14:0] trunc_ln39_2_fu_2525_p1;
wire   [14:0] tmp116_fu_2529_p2;
wire   [14:0] trunc_ln39_1_fu_2521_p1;
wire   [15:0] p_shl3_fu_2544_p3;
wire   [15:0] p_shl4_fu_2551_p3;
wire   [15:0] add_ln39_fu_2558_p2;
wire   [15:0] acc_fu_2564_p2;
wire   [15:0] grp_fu_2574_p0;
wire   [15:0] grp_fu_2574_p1;
wire   [3:0] grp_fu_2574_p2;
wire   [15:0] grp_fu_2574_p3;
reg   [27:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_126 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_124 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_123 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_122 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_121 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_120 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_118 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_117 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_116 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_115 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_114 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_113 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_112 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_111 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_110 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_109 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_108 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_106 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_105 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_104 = 15'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_103 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_102 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_101 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_100 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_99 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_98 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_95 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_94 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_93 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_92 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_91 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_90 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_89 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_88 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_87 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_86 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_85 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_84 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_83 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_82 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_81 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_79 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_78 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_77 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_76 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_75 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_74 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_73 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_72 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_71 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_70 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_69 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_68 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_67 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_66 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_65 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_64 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_63 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_62 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_61 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_60 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_59 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_58 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_57 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_56 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_55 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_54 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_53 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_52 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_51 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_50 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_48 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_47 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_46 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_45 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_44 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_43 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_42 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_41 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_40 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_39 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_38 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_37 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_36 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_35 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_34 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_33 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_32 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_31 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_30 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_29 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_28 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_27 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_26 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_25 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_24 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_23 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_22 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_21 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_20 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_19 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_18 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_17 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_16 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_15 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_14 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_13 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_12 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_11 = 16'd0;
#0 p_ZZ3firP6ap_intILi17EES0_E9shift_reg_10 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_9 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_8 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_7 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_6 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_5 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_4 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_3 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_2 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg_1 = 16'd0;
#0 fir_ap_int_17_ap_int_17_shift_reg = 16'd0;
end

fir_ama_addmuladd_16ns_16ns_4ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
ama_addmuladd_16ns_16ns_4ns_16ns_16_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2574_p0),
    .din1(grp_fu_2574_p1),
    .din2(grp_fu_2574_p2),
    .din3(grp_fu_2574_p3),
    .ce(1'b1),
    .dout(grp_fu_2574_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        add_ln39_2_reg_2919 <= add_ln39_2_fu_2218_p2;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_25 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_24;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_26 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_25;
        tmp101_reg_2914 <= tmp101_fu_2202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        empty_58_reg_2964 <= empty_58_fu_2540_p1;
        fir_ap_int_17_ap_int_17_shift_reg_8 <= fir_ap_int_17_ap_int_17_shift_reg_7_load_reg_2878;
        fir_ap_int_17_ap_int_17_shift_reg_9 <= fir_ap_int_17_ap_int_17_shift_reg_8;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_10 <= fir_ap_int_17_ap_int_17_shift_reg_9;
        tmp117_reg_2959 <= tmp117_fu_2534_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        fir_ap_int_17_ap_int_17_shift_reg <= trunc_ln15_reg_2633;
        fir_ap_int_17_ap_int_17_shift_reg_1 <= fir_ap_int_17_ap_int_17_shift_reg;
        fir_ap_int_17_ap_int_17_shift_reg_2 <= fir_ap_int_17_ap_int_17_shift_reg_1;
        fir_ap_int_17_ap_int_17_shift_reg_3 <= fir_ap_int_17_ap_int_17_shift_reg_2;
        fir_ap_int_17_ap_int_17_shift_reg_4 <= fir_ap_int_17_ap_int_17_shift_reg_3;
        fir_ap_int_17_ap_int_17_shift_reg_5 <= fir_ap_int_17_ap_int_17_shift_reg_4;
        fir_ap_int_17_ap_int_17_shift_reg_6 <= fir_ap_int_17_ap_int_17_shift_reg_5;
        fir_ap_int_17_ap_int_17_shift_reg_7 <= fir_ap_int_17_ap_int_17_shift_reg_6;
        fir_ap_int_17_ap_int_17_shift_reg_7_load_reg_2878 <= fir_ap_int_17_ap_int_17_shift_reg_7;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_31 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_30;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_32 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_31;
        tmp171_reg_2888 <= tmp171_fu_2063_p2;
        tmp1891_reg_2894 <= tmp1891_fu_2078_p2;
        tmp95_reg_2883 <= tmp95_fu_2035_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        fir_ap_int_17_ap_int_17_shift_reg_12_reg_2720 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_81;
        fir_ap_int_17_ap_int_17_shift_reg_19_reg_2726 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_64;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_100 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_99;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_101 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_100;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_102 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_101;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_64 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_63;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_71 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_70;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_72 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_71;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_81 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80_load_reg_2699;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_85 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_84;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_86 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_85;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_87 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_86;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_88 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_87;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_98 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97_load_reg_2694;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_99 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_98;
        tmp135_reg_2737 <= tmp135_fu_1182_p2;
        tmp162_reg_2747 <= tmp162_fu_1205_p2;
        tmp180_reg_2752 <= tmp180_fu_1217_p2;
        tmp38_reg_2742 <= tmp38_fu_1194_p2;
        tmp78_reg_2732 <= tmp78_fu_1171_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        fir_ap_int_17_ap_int_17_shift_reg_14_reg_2679 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_74;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_73 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_72;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_74 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_73;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_89 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_88;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_90 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_89;
        tmp28_reg_2689 <= tmp28_fu_860_p2;
        tmp69_reg_2684 <= tmp69_fu_848_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        fir_ap_int_17_ap_int_17_shift_reg_18_reg_2777 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_65;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_60 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_59;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_61 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_60;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_65 <= fir_ap_int_17_ap_int_17_shift_reg_19_reg_2726;
        tmp141_reg_2787 <= tmp141_fu_1399_p2;
        tmp82_reg_2782 <= tmp82_fu_1388_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        fir_ap_int_17_ap_int_17_shift_reg_31_reg_2798 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_42;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_39 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_38;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_40 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_39;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_41 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_40;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_42 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_41;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_48;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49_load_reg_2792 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_53 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_52;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_54 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_53;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_55 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_54;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_56 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_55;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_57 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_56;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_58 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_57;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_59 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_58;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_66 <= fir_ap_int_17_ap_int_17_shift_reg_18_reg_2777;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_67 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_66;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_68 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_67;
        tmp120_reg_2823 <= tmp120_fu_1629_p2;
        tmp143_reg_2818 <= tmp143_fu_1617_p2;
        tmp166_reg_2828 <= tmp166_fu_1640_p2;
        tmp184_reg_2833 <= tmp184_fu_1651_p2;
        tmp35_reg_2813 <= tmp35_fu_1606_p2;
        tmp84_reg_2808 <= tmp84_fu_1594_p2;
        trunc_ln39_33_reg_2803 <= trunc_ln39_33_fu_1573_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_103 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_102;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_104 <= trunc_ln33_fu_870_p1;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_75 <= fir_ap_int_17_ap_int_17_shift_reg_14_reg_2679;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_76 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_75;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_77 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_76;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_78 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_77;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_79 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_78;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_79;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80_load_reg_2699 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96_load_reg_2658;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97_load_reg_2694 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97;
        tmp133_reg_2715 <= tmp133_fu_1018_p2;
        tmp23_reg_2705 <= tmp23_fu_989_p2;
        tmp26_reg_2710 <= tmp26_fu_1001_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_105 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_104;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_106 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_105;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107_load_reg_2585 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107;
        tmp21_reg_2591 <= tmp21_fu_343_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_108 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107_load_reg_2585;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_109 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_108;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_110 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_109;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_111 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_110;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_112 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_111;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_113 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_112;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_114 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_113;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_115 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_114;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_116 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_115;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_117 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_116;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_118 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_117;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_118;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119_load_reg_2602 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_123 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_122;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_124 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_123;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_124;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125_load_reg_2596 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125;
        tmp10_reg_2613 <= tmp10_fu_520_p2;
        tmp14_reg_2618 <= tmp14_fu_532_p2;
        tmp16_reg_2623 <= tmp16_fu_544_p2;
        tmp18_reg_2628 <= tmp18_fu_561_p2;
        tmp5_reg_2608 <= tmp5_fu_508_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_11 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_10;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_12 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_11;
        tmp115_reg_2954 <= tmp115_fu_2490_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_120 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119_load_reg_2602;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_121 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_120;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_122 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_121;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_126 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125_load_reg_2596;
        tmp12_reg_2648 <= tmp12_fu_644_p2;
        tmp2_reg_2638 <= tmp2_fu_619_p2;
        tmp7_reg_2643 <= tmp7_fu_635_p2;
        trunc_ln15_reg_2633 <= trunc_ln15_fu_566_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_13 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_12;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_14 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_13;
        tmp113_reg_2949 <= tmp113_fu_2451_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_15 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_14;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_16 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_15;
        tmp111_reg_2944 <= tmp111_fu_2412_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_17 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_16;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_18 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_17;
        tmp109_reg_2939 <= tmp109_fu_2373_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_19 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_18;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_20 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_19;
        tmp107_reg_2934 <= tmp107_fu_2334_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_21 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_20;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_22 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_21;
        tmp105_reg_2929 <= tmp105_fu_2295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_23 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_22;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_24 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_23;
        tmp103_reg_2924 <= tmp103_fu_2256_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_27 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_26;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_28 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_27;
        tmp99_reg_2904 <= tmp99_fu_2156_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_29 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_28;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_30 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_29;
        tmp97_reg_2899 <= tmp97_fu_2117_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_33 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_32;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_34 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_33;
        tmp149_reg_2873 <= tmp149_fu_1913_p2;
        tmp93_reg_2868 <= tmp93_fu_1903_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_35 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_34;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_36 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_35;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_37 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_36;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_38 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_37;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_43 <= fir_ap_int_17_ap_int_17_shift_reg_31_reg_2798;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_44 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_43;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_45 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_44;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_46 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_45;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_47 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_46;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_48 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_47;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_50 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49_load_reg_2792;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_51 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_50;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_52 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_51;
        tmp147_reg_2853 <= tmp147_fu_1840_p2;
        tmp169_reg_2858 <= tmp169_fu_1856_p2;
        tmp187_reg_2863 <= tmp187_fu_1873_p2;
        tmp31_reg_2838 <= tmp31_fu_1813_p2;
        tmp32_reg_2843 <= tmp32_fu_1819_p2;
        tmp33_reg_2848 <= tmp33_fu_1831_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_62 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_61;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_63 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_62;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_69 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_68;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_70 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_69;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_82 <= fir_ap_int_17_ap_int_17_shift_reg_12_reg_2720;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_83 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_82;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_84 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_83;
        tmp139_reg_2762 <= tmp139_fu_1319_p2;
        tmp164_reg_2767 <= tmp164_fu_1330_p2;
        tmp182_reg_2772 <= tmp182_fu_1341_p2;
        tmp80_reg_2757 <= tmp80_fu_1309_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_91 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_90;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_92 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_91;
        tmp67_reg_2674 <= tmp67_fu_773_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_93 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_92;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_94 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_93;
        tmp65_reg_2669 <= tmp65_fu_734_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_95 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_94;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_95;
        p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96_load_reg_2658 <= p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96;
        tmp63_reg_2664 <= tmp63_fu_695_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp61_reg_2653 <= tmp61_fu_653_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_2564_p2 = (add_ln39_2_reg_2919 + add_ln39_fu_2558_p2);

assign add_ln39_2_fu_2218_p0 = grp_fu_2574_p4;

assign add_ln39_2_fu_2218_p2 = ($signed(add_ln39_2_fu_2218_p0) + $signed(tmp172_fu_2213_p2));

assign add_ln39_fu_2558_p2 = (p_shl3_fu_2544_p3 + p_shl4_fu_2551_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign empty_48_fu_1777_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_34[12:0];

assign empty_49_fu_1781_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_37[12:0];

assign empty_50_fu_1805_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_50[12:0];

assign empty_51_fu_1569_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_53[12:0];

assign empty_52_fu_1585_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_66[12:0];

assign empty_53_fu_1296_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_69[12:0];

assign empty_54_fu_1300_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_82[12:0];

assign empty_55_fu_1155_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_85[12:0];

assign empty_56_fu_1159_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_98[12:0];

assign empty_57_fu_1163_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_101[12:0];

assign empty_58_fu_2540_p1 = tmp117_fu_2534_p2[12:0];

assign empty_59_fu_2208_p2 = tmp171_reg_2888 << 16'd2;

assign empty_60_fu_2074_p1 = fir_ap_int_17_ap_int_17_shift_reg_2[12:0];

assign empty_fu_2018_p1 = fir_ap_int_17_ap_int_17_shift_reg_5[12:0];

assign grp_fu_2574_p0 = (fir_ap_int_17_ap_int_17_shift_reg_1 + fir_ap_int_17_ap_int_17_shift_reg);

assign grp_fu_2574_p1 = (tmp150_fu_2041_p2 - fir_ap_int_17_ap_int_17_shift_reg_6);

assign grp_fu_2574_p2 = 16'd11;

assign grp_fu_2574_p3 = {{tmp1891_reg_2894}, {3'd0}};

assign p_shl3_fu_2544_p3 = {{empty_58_reg_2964}, {3'd0}};

assign p_shl4_fu_2551_p3 = {{tmp117_reg_2959}, {1'd0}};

assign tmp100_fu_2197_p2 = (tmp99_reg_2904 - trunc_ln39_18_fu_2193_p1);

assign tmp101_fu_2202_p2 = (tmp100_fu_2197_p2 - trunc_ln39_17_fu_2189_p1);

assign tmp102_fu_2251_p2 = (tmp101_reg_2914 - trunc_ln39_16_fu_2247_p1);

assign tmp103_fu_2256_p2 = (tmp102_fu_2251_p2 - trunc_ln39_15_fu_2243_p1);

assign tmp104_fu_2290_p2 = (tmp103_reg_2924 - trunc_ln39_14_fu_2286_p1);

assign tmp105_fu_2295_p2 = (tmp104_fu_2290_p2 - trunc_ln39_13_fu_2282_p1);

assign tmp106_fu_2329_p2 = (tmp105_reg_2929 - trunc_ln39_12_fu_2325_p1);

assign tmp107_fu_2334_p2 = (tmp106_fu_2329_p2 - trunc_ln39_11_fu_2321_p1);

assign tmp108_fu_2368_p2 = (tmp107_reg_2934 - trunc_ln39_10_fu_2364_p1);

assign tmp109_fu_2373_p2 = (tmp108_fu_2368_p2 - trunc_ln39_9_fu_2360_p1);

assign tmp10_fu_520_p2 = (tmp11_fu_514_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_118);

assign tmp110_fu_2407_p2 = (tmp109_reg_2939 - trunc_ln39_8_fu_2403_p1);

assign tmp111_fu_2412_p2 = (tmp110_fu_2407_p2 - trunc_ln39_7_fu_2399_p1);

assign tmp112_fu_2446_p2 = (tmp111_reg_2944 - trunc_ln39_6_fu_2442_p1);

assign tmp113_fu_2451_p2 = (tmp112_fu_2446_p2 - trunc_ln39_5_fu_2438_p1);

assign tmp114_fu_2485_p2 = (tmp113_reg_2949 - trunc_ln39_4_fu_2481_p1);

assign tmp115_fu_2490_p2 = (tmp114_fu_2485_p2 - trunc_ln39_3_fu_2477_p1);

assign tmp116_fu_2529_p2 = (tmp115_reg_2954 - trunc_ln39_2_fu_2525_p1);

assign tmp117_fu_2534_p2 = (tmp116_fu_2529_p2 - trunc_ln39_1_fu_2521_p1);

assign tmp119_fu_1836_p2 = (tmp143_reg_2818 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_49_load_reg_2792);

assign tmp11_fu_514_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_117 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_116);

assign tmp120_fu_1629_p2 = (tmp121_fu_1623_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_48);

assign tmp121_fu_1623_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_39 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_38);

assign tmp123_fu_1324_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_83 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_68);

assign tmp124_fu_1845_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_51 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_36);

assign tmp125_fu_1335_p2 = (empty_54_fu_1300_p1 + empty_53_fu_1296_p1);

assign tmp126_fu_1862_p2 = (empty_50_fu_1805_p1 + empty_49_fu_1781_p1);

assign tmp12_fu_644_p2 = (tmp18_reg_2628 + tmp13_fu_640_p2);

assign tmp131_fu_1006_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_102 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_103);

assign tmp132_fu_1012_p2 = (tmp131_fu_1006_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_97);

assign tmp133_fu_1018_p2 = (tmp132_fu_1012_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_96_load_reg_2658);

assign tmp134_fu_1177_p2 = (tmp133_reg_2715 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_87);

assign tmp135_fu_1182_p2 = (tmp134_fu_1177_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_86);

assign tmp139_fu_1319_p2 = (tmp38_reg_2742 + tmp37_fu_1315_p2);

assign tmp13_fu_640_p2 = (tmp16_reg_2623 + tmp14_reg_2618);

assign tmp140_fu_1394_p2 = (tmp139_reg_2762 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_65);

assign tmp141_fu_1399_p2 = (tmp140_fu_1394_p2 - fir_ap_int_17_ap_int_17_shift_reg_19_reg_2726);

assign tmp142_fu_1612_p2 = (tmp141_reg_2787 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_55);

assign tmp143_fu_1617_p2 = (tmp142_fu_1612_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_54);

assign tmp147_fu_1840_p2 = (tmp120_reg_2823 + tmp119_fu_1836_p2);

assign tmp148_fu_1908_p2 = (tmp147_reg_2853 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_33);

assign tmp149_fu_1913_p2 = (tmp148_fu_1908_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_32);

assign tmp14_fu_532_p2 = (tmp15_fu_526_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_115);

assign tmp150_fu_2041_p2 = (tmp149_reg_2873 - fir_ap_int_17_ap_int_17_shift_reg_7);

assign tmp15_fu_526_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_114 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_113);

assign tmp161_fu_1199_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_100 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_99);

assign tmp162_fu_1205_p2 = (tmp161_fu_1199_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_84);

assign tmp164_fu_1330_p2 = (tmp123_fu_1324_p2 + tmp162_reg_2747);

assign tmp165_fu_1635_p2 = (tmp164_reg_2767 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_67);

assign tmp166_fu_1640_p2 = (tmp165_fu_1635_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_52);

assign tmp168_fu_1851_p2 = (tmp124_fu_1845_p2 + tmp166_reg_2828);

assign tmp169_fu_1856_p2 = (tmp168_fu_1851_p2 - p_ZZ3firP6ap_intILi17EES0_E9shift_reg_35);

assign tmp16_fu_544_p2 = (tmp17_fu_538_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_112);

assign tmp170_fu_2058_p2 = (tmp169_reg_2858 - fir_ap_int_17_ap_int_17_shift_reg_4);

assign tmp171_fu_2063_p2 = (tmp170_fu_2058_p2 + fir_ap_int_17_ap_int_17_shift_reg_3);

assign tmp172_fu_2213_p2 = (empty_59_fu_2208_p2 - tmp171_reg_2888);

assign tmp179_fu_1211_p2 = (empty_57_fu_1163_p1 - empty_56_fu_1159_p1);

assign tmp17_fu_538_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_111 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_110);

assign tmp180_fu_1217_p2 = (tmp179_fu_1211_p2 - empty_55_fu_1155_p1);

assign tmp182_fu_1341_p2 = (tmp125_fu_1335_p2 + tmp180_reg_2752);

assign tmp183_fu_1646_p2 = (tmp182_reg_2772 - empty_52_fu_1585_p1);

assign tmp184_fu_1651_p2 = (tmp183_fu_1646_p2 - empty_51_fu_1569_p1);

assign tmp186_fu_1868_p2 = (tmp126_fu_1862_p2 + tmp184_reg_2833);

assign tmp187_fu_1873_p2 = (tmp186_fu_1868_p2 - empty_48_fu_1777_p1);

assign tmp188_fu_2069_p2 = (tmp187_reg_2863 - empty_fu_2018_p1);

assign tmp1891_fu_2078_p2 = (tmp188_fu_2069_p2 + empty_60_fu_2074_p1);

assign tmp18_fu_561_p2 = (tmp21_reg_2591 + tmp19_fu_555_p2);

assign tmp19_fu_555_p2 = (tmp20_fu_550_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_109);

assign tmp1_fu_649_p2 = (tmp7_reg_2643 + tmp2_reg_2638);

assign tmp20_fu_550_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_108 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_107_load_reg_2585);

assign tmp21_fu_343_p2 = (tmp22_fu_337_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_106);

assign tmp22_fu_337_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_105 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_104);

assign tmp23_fu_989_p2 = (tmp25_fu_983_p2 + tmp24_fu_978_p2);

assign tmp24_fu_978_p2 = (tmp69_reg_2684 + trunc_ln39_48_fu_974_p1);

assign tmp25_fu_983_p2 = (trunc_ln39_47_fu_970_p1 + trunc_ln39_46_fu_966_p1);

assign tmp26_fu_1001_p2 = (tmp28_reg_2689 + tmp27_fu_995_p2);

assign tmp27_fu_995_p2 = (trunc_ln39_45_fu_962_p1 + trunc_ln39_44_fu_958_p1);

assign tmp28_fu_860_p2 = (tmp29_fu_854_p2 + trunc_ln39_43_fu_831_p1);

assign tmp29_fu_854_p2 = (trunc_ln39_42_fu_827_p1 + trunc_ln39_41_fu_823_p1);

assign tmp2_fu_619_p2 = (tmp5_reg_2608 + tmp3_fu_613_p2);

assign tmp30_fu_1899_p2 = (tmp32_reg_2843 + tmp31_reg_2838);

assign tmp31_fu_1813_p2 = (tmp85_fu_1809_p2 + trunc_ln39_32_fu_1801_p1);

assign tmp32_fu_1819_p2 = (trunc_ln39_31_fu_1797_p1 + trunc_ln39_30_fu_1793_p1);

assign tmp33_fu_1831_p2 = (tmp35_reg_2813 + tmp34_fu_1825_p2);

assign tmp34_fu_1825_p2 = (trunc_ln39_29_fu_1789_p1 + trunc_ln39_28_fu_1785_p1);

assign tmp35_fu_1606_p2 = (tmp36_fu_1600_p2 + trunc_ln39_27_fu_1565_p1);

assign tmp36_fu_1600_p2 = (trunc_ln39_26_fu_1561_p1 + trunc_ln39_25_fu_1557_p1);

assign tmp37_fu_1315_p2 = (tmp135_reg_2737 + fir_ap_int_17_ap_int_17_shift_reg_12_reg_2720);

assign tmp38_fu_1194_p2 = (tmp39_fu_1188_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_80_load_reg_2699);

assign tmp39_fu_1188_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_71 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_70);

assign tmp3_fu_613_p2 = (tmp4_fu_608_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_126);

assign tmp4_fu_608_p2 = (trunc_ln39_fu_604_p1 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_125_load_reg_2596);

assign tmp5_fu_508_p2 = (tmp6_fu_502_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_124);

assign tmp61_fu_653_p2 = (tmp12_reg_2648 + tmp1_fu_649_p2);

assign tmp62_fu_690_p2 = (tmp61_reg_2653 - trunc_ln39_56_fu_686_p1);

assign tmp63_fu_695_p2 = (tmp62_fu_690_p2 - trunc_ln39_55_fu_682_p1);

assign tmp64_fu_729_p2 = (tmp63_reg_2664 - trunc_ln39_54_fu_725_p1);

assign tmp65_fu_734_p2 = (tmp64_fu_729_p2 - trunc_ln39_53_fu_721_p1);

assign tmp66_fu_768_p2 = (tmp65_reg_2669 - trunc_ln39_52_fu_764_p1);

assign tmp67_fu_773_p2 = (tmp66_fu_768_p2 - trunc_ln39_51_fu_760_p1);

assign tmp68_fu_843_p2 = (tmp67_reg_2674 - trunc_ln39_50_fu_839_p1);

assign tmp69_fu_848_p2 = (tmp68_fu_843_p2 - trunc_ln39_49_fu_835_p1);

assign tmp6_fu_502_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_123 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_122);

assign tmp77_fu_1167_p2 = (tmp26_reg_2710 + tmp23_reg_2705);

assign tmp78_fu_1171_p2 = (tmp77_fu_1167_p2 - trunc_ln39_40_fu_1151_p1);

assign tmp79_fu_1304_p2 = (tmp78_reg_2732 - trunc_ln39_39_fu_1292_p1);

assign tmp7_fu_635_p2 = (tmp10_reg_2613 + tmp8_fu_629_p2);

assign tmp80_fu_1309_p2 = (tmp79_fu_1304_p2 - trunc_ln39_38_fu_1288_p1);

assign tmp81_fu_1383_p2 = (tmp80_reg_2757 - trunc_ln39_37_fu_1379_p1);

assign tmp82_fu_1388_p2 = (tmp81_fu_1383_p2 - trunc_ln39_36_fu_1375_p1);

assign tmp83_fu_1589_p2 = (tmp82_reg_2782 - trunc_ln39_35_fu_1581_p1);

assign tmp84_fu_1594_p2 = (tmp83_fu_1589_p2 - trunc_ln39_34_fu_1577_p1);

assign tmp85_fu_1809_p2 = (tmp84_reg_2808 - trunc_ln39_33_reg_2803);

assign tmp8_fu_629_p2 = (tmp9_fu_624_p2 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_121);

assign tmp93_fu_1903_p2 = (tmp33_reg_2848 + tmp30_fu_1899_p2);

assign tmp94_fu_2030_p2 = (tmp93_reg_2868 - trunc_ln39_24_fu_2026_p1);

assign tmp95_fu_2035_p2 = (tmp94_fu_2030_p2 - trunc_ln39_23_fu_2022_p1);

assign tmp96_fu_2112_p2 = (tmp95_reg_2883 - trunc_ln39_22_fu_2108_p1);

assign tmp97_fu_2117_p2 = (tmp96_fu_2112_p2 - trunc_ln39_21_fu_2104_p1);

assign tmp98_fu_2151_p2 = (tmp97_reg_2899 - trunc_ln39_20_fu_2147_p1);

assign tmp99_fu_2156_p2 = (tmp98_fu_2151_p2 - trunc_ln39_19_fu_2143_p1);

assign tmp9_fu_624_p2 = (p_ZZ3firP6ap_intILi17EES0_E9shift_reg_120 + p_ZZ3firP6ap_intILi17EES0_E9shift_reg_119_load_reg_2602);

assign trunc_ln15_fu_566_p1 = x[15:0];

assign trunc_ln33_fu_870_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_103[14:0];

assign trunc_ln39_10_fu_2364_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_17[14:0];

assign trunc_ln39_11_fu_2321_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_18[14:0];

assign trunc_ln39_12_fu_2325_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_19[14:0];

assign trunc_ln39_13_fu_2282_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_20[14:0];

assign trunc_ln39_14_fu_2286_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_21[14:0];

assign trunc_ln39_15_fu_2243_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_22[14:0];

assign trunc_ln39_16_fu_2247_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_23[14:0];

assign trunc_ln39_17_fu_2189_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_24[14:0];

assign trunc_ln39_18_fu_2193_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_25[14:0];

assign trunc_ln39_19_fu_2143_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_26[14:0];

assign trunc_ln39_1_fu_2521_p1 = fir_ap_int_17_ap_int_17_shift_reg_8[14:0];

assign trunc_ln39_20_fu_2147_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_27[14:0];

assign trunc_ln39_21_fu_2104_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_28[14:0];

assign trunc_ln39_22_fu_2108_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_29[14:0];

assign trunc_ln39_23_fu_2022_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_30[14:0];

assign trunc_ln39_24_fu_2026_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_31[14:0];

assign trunc_ln39_25_fu_1557_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_40[14:0];

assign trunc_ln39_26_fu_1561_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_41[14:0];

assign trunc_ln39_27_fu_1565_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_42[14:0];

assign trunc_ln39_28_fu_1785_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_43[14:0];

assign trunc_ln39_29_fu_1789_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_44[14:0];

assign trunc_ln39_2_fu_2525_p1 = fir_ap_int_17_ap_int_17_shift_reg_9[14:0];

assign trunc_ln39_30_fu_1793_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_45[14:0];

assign trunc_ln39_31_fu_1797_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_46[14:0];

assign trunc_ln39_32_fu_1801_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_47[14:0];

assign trunc_ln39_33_fu_1573_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_56[14:0];

assign trunc_ln39_34_fu_1577_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_57[14:0];

assign trunc_ln39_35_fu_1581_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_58[14:0];

assign trunc_ln39_36_fu_1375_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_59[14:0];

assign trunc_ln39_37_fu_1379_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_60[14:0];

assign trunc_ln39_38_fu_1288_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_61[14:0];

assign trunc_ln39_39_fu_1292_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_62[14:0];

assign trunc_ln39_3_fu_2477_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_10[14:0];

assign trunc_ln39_40_fu_1151_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_63[14:0];

assign trunc_ln39_41_fu_823_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_72[14:0];

assign trunc_ln39_42_fu_827_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_73[14:0];

assign trunc_ln39_43_fu_831_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_74[14:0];

assign trunc_ln39_44_fu_958_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_75[14:0];

assign trunc_ln39_45_fu_962_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_76[14:0];

assign trunc_ln39_46_fu_966_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_77[14:0];

assign trunc_ln39_47_fu_970_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_78[14:0];

assign trunc_ln39_48_fu_974_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_79[14:0];

assign trunc_ln39_49_fu_835_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_88[14:0];

assign trunc_ln39_4_fu_2481_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_11[14:0];

assign trunc_ln39_50_fu_839_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_89[14:0];

assign trunc_ln39_51_fu_760_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_90[14:0];

assign trunc_ln39_52_fu_764_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_91[14:0];

assign trunc_ln39_53_fu_721_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_92[14:0];

assign trunc_ln39_54_fu_725_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_93[14:0];

assign trunc_ln39_55_fu_682_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_94[14:0];

assign trunc_ln39_56_fu_686_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_95[14:0];

assign trunc_ln39_5_fu_2438_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_12[14:0];

assign trunc_ln39_6_fu_2442_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_13[14:0];

assign trunc_ln39_7_fu_2399_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_14[14:0];

assign trunc_ln39_8_fu_2403_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_15[14:0];

assign trunc_ln39_9_fu_2360_p1 = p_ZZ3firP6ap_intILi17EES0_E9shift_reg_16[14:0];

assign trunc_ln39_fu_604_p1 = x[14:0];

assign y = $signed(acc_fu_2564_p2);

endmodule //fir
